# .github/workflows/deploy.yml
name: 🚀 Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read      # to clone the repo
  pages: write        # to publish Pages
  id-token: write     # for OIDC token

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install, build, and package Astro site
        uses: withastro/action@v4
        with:
          package-manager: npm

      - name: Disable Jekyll
        run: echo > ./dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
