name: 🚀 Deploy Astro to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read      # checkout
  pages: write        # deploy
  id-token: write     # for OIDC

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and package Astro site
        uses: withastro/action@v4
        # by default this:
        #  • runs `npm ci` (or yarn)
        #  • runs `npm run build`
        #  • uploads ./dist as the Pages artifact

      - name: Disable Jekyll
        run: echo > ./dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
